branch-defaults:
  master:
    environment: MyReactApp-env
global:
  application_name: my-react-app
  default_platform: Docker running on 64bit Amazon Linux 2/4.0.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: Docker running on 64bit Amazon Linux 2
  platform_version: 4.0.6
  sc: git
  workspace_type: Application

option_settings:
  aws:elasticbeanstalk:environment:
    ServiceRole: aws-elasticbeanstalk-service-role
  aws:elasticbeanstalk:environment:process:default:
    HealthCheckPath: /
    Port: 80
    Protocol: HTTP
  aws:elasticbeanstalk:cloudwatch:logs:
    StreamLogs: true
